KEYWORD_TO_CHART = {
    "camembert": "pie",
    "diagramme en secteurs": "pie",
    "pie": "pie",
    "donut": "doncolumn",    "donut": "donut",
    "colonne": "column",
    "courbe": "line",
    "line": "line",
    "aire": "area",
    "area": "area",
    "histogramme": "hist",
    "hist": "hist",
    "nuage de points": "scatter",
    "scatter": "scatter",
    "bulle": "bubble",
    "bubble": "bubble",
    "carte": "map",
    "map": "map",
    "treemap": "treemap",
    "arborescente": "treemap",
    "funnel": "funnel",
    "entonnoir": "funnel",
    "waterfall": "waterfall",
    "cascade": "waterfall",
    "pareto": "pareto",
    "heatmap": "heatmap",
    "carte thermique": "heatmap",
    "gauge": "gauge",
    "jauge": "gauge",
    "radar": "radar",
    "sankey": "sankey",
    "flux": "sankey",
}
    "anneau": "donut",
    "bar": "bar",
    "barres": "bar",
